In [242]:
import numpy as np
import matplotlib.pyplot as plt

In [243]:
l=4


In [244]:
def isValid(s,a):


    return (s+a>=0 and s+a<l)
def tau(s,a):

    if(a==0):#up
        if(isValid(s[0],-1)):
            return (s[0]-1,s[1])
    elif(a==1):#down
        if(isValid(s[0],+1)):
            return (s[0]+1,s[1])
    elif(a==2):#left
        if(isValid(s[1],-1)):
            return (s[0],s[1]-1)    
    elif(a==3):#right
        if(isValid(s[1],1)):
            return (s[0],s[1]+1)    
    return(s)

def calc_policy(Q):
    pi = np.full((l, l), 0)
    for i in range(0,l):
        for j in range(0,l):
            pos=idq((i,j))
            action=np.argmax(Q[pos,:])
            pi[i,j]=action
            if(pos==5 or pos==13 or pos==15):
                pi[i,j]=-1

    return pi.astype(int)  

def idq(s):

    return ((s[0])*l)+s[1]


In [245]:


Q = np.full((l*l, 4), 0.5)
Q[5,:]=-1
Q[13,:]=-1
Q[15,:]=1
Q


array([[ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [-1. , -1. , -1. , -1. ],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [-1. , -1. , -1. , -1. ],
       [ 0.5,  0.5,  0.5,  0.5],
       [10. , 10. , 10. , 10. ]])

In [246]:
gamma = 0.9
initial_state = [0,0]

In [247]:
def update(current_state, action, gamma): 
  
    next_state = tau(current_state, action)



    current_statePos=idq(current_state)
    next_statePos=idq(next_state)
    Q[current_statePos, action] = Q[current_statePos, action] - gamma * (Q[current_statePos, action]- np.average(Q[next_statePos, :]))
    return next_state

In [248]:

def learning_function(Q, gamma):

    current_state = initial_state
    pos=idq(current_state)  


    i=0

    

    while pos != 5 and pos != 13 and pos != 15 :
        i+=1
        print("iteration: ",i)
        if(i%2==0):
            print("r")
            action = np.random.choice([0, 1,2,3])
        else:  
            print("m")  

            action = np.argmax(Q[pos, :])

        current_state = update(current_state, action, gamma)
        pos=idq(current_state) 
        print("current state: ",current_state,pos,(pos != 5 or pos != 13 or pos != 15))
    return Q

In [249]:
for i in range(100):
    Q = learning_function(Q, gamma)
    


iteration:  1
m
current state:  [0, 0] 0 True
iteration:  2
r
current state:  [0, 0] 0 True
iteration:  3
m
current state:  [0, 0] 0 True
iteration:  4
r
current state:  (0, 1) 1 True
iteration:  5
m
current state:  (0, 1) 1 True
iteration:  6
r
current state:  (0, 2) 2 True
iteration:  7
m
current state:  (0, 2) 2 True
iteration:  8
r
current state:  (0, 3) 3 True
iteration:  9
m
current state:  (0, 3) 3 True
iteration:  10
r
current state:  (0, 3) 3 True
iteration:  11
m
current state:  (0, 3) 3 True
iteration:  12
r
current state:  (0, 3) 3 True
iteration:  13
m
current state:  (0, 3) 3 True
iteration:  14
r
current state:  (0, 3) 3 True
iteration:  15
m
current state:  (0, 3) 3 True
iteration:  16
r
current state:  (0, 3) 3 True
iteration:  17
m
current state:  (0, 3) 3 True
iteration:  18
r
current state:  (0, 3) 3 True
iteration:  19
m
current state:  (0, 3) 3 True
iteration:  20
r
current state:  (1, 3) 7 True
iteration:  21
m
current state:  (0, 3) 3 True
iteration:  22
r
curre

In [250]:
policy=calc_policy(Q)
policy

array([[ 3,  3,  3,  1],
       [ 1, -1,  3,  1],
       [ 3,  3,  3,  1],
       [ 0, -1,  0, -1]])

In [251]:
print(Q) 

[[-0.35470872 -0.37448183 -0.3546634  -0.29102862]
 [-0.29290204 -1.         -0.34421069  0.47470725]
 [ 0.46332215  0.50396969 -0.29802599  1.23227625]
 [ 1.19614508  2.04974655  0.45668875  1.23225786]
 [-0.2171002  -0.21357269 -0.42471825 -0.985     ]
 [-1.         -1.         -1.         -1.        ]
 [ 0.39393696  0.42465752 -0.85        2.05016414]
 [ 1.23032591  4.42150935  0.5046829   2.04980471]
 [-0.42442856 -0.4391549  -0.25793762 -0.15272704]
 [-0.85       -0.85       -0.03887078  1.18765513]
 [ 0.41199969  0.2100292  -0.16530746  4.42139017]
 [ 2.04980929 10.          1.21864064  4.41868129]
 [-0.26864061 -0.40357278 -0.28819204 -0.99985   ]
 [-1.         -1.         -1.         -1.        ]
 [ 1.14487438  0.1948599  -0.85        0.5       ]
 [10.         10.         10.         10.        ]]
